/* AetherArch C API — auto-generated by cbindgen. Do not edit. */
/* SPDX-License-Identifier: Apache-2.0 OR Commercial */

#ifndef AETHER_H
#define AETHER_H

/* Warning: this file is auto-generated by cbindgen. Do not modify. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Operation completed successfully.
 */
#define AETHER_OK 0

/**
 * A required pointer argument was NULL.
 */
#define AETHER_ERR_NULL_PTR -1

/**
 * A string argument contained invalid UTF-8.
 */
#define AETHER_ERR_INVALID_UTF8 -2

/**
 * An I/O error occurred (file not found, permission denied, etc.).
 */
#define AETHER_ERR_IO -3

/**
 * Compression or decompression failed.
 */
#define AETHER_ERR_COMPRESSION -4

/**
 * Invalid or unsupported predictor ID.
 */
#define AETHER_ERR_INVALID_PREDICTOR -5

/**
 * Archive format error (corrupt header, bad magic, etc.).
 */
#define AETHER_ERR_ARCHIVE -6

/**
 * Path traversal detected in archive entry.
 */
#define AETHER_ERR_PATH_TRAVERSAL -7

/**
 * Opaque compressor handle.
 */
typedef struct AetherCompressor AetherCompressor;

/**
 * Opaque decompressor handle.
 */
typedef struct AetherDecompressor AetherDecompressor;

/**
 * File information returned by `aether_list`.
 */
typedef struct AetherFileInfo {
  /**
   * File path (C string, owned by this struct).
   */
  char *path;
  /**
   * Original uncompressed size in bytes.
   */
  uint64_t original_size;
  /**
   * Unix permissions (e.g. 0o644).
   */
  uint32_t permissions;
  /**
   * Last modification time (Unix timestamp).
   */
  int64_t mtime;
} AetherFileInfo;

/**
 * Opaque file list handle returned by [`aether_list`].
 *
 * # H3 security fix
 *
 * Embeds the entry count so [`aether_file_list_free`] does not depend on
 * the caller passing the correct count, eliminating heap-corruption risk.
 *
 * # Fix #12: safety warning
 *
 * **Do not modify `count` or `entries` after receiving this struct.**
 * Callers should use [`aether_file_list_count`] and
 * [`aether_file_list_get`] to access entries safely.
 * Mutating `count` before calling [`aether_file_list_free`] causes
 * undefined behavior (heap corruption).
 */
typedef struct AetherFileList {
  /**
   * Pointer to the array of [`AetherFileInfo`] entries.
   * **Read-only** — do not modify.
   */
  struct AetherFileInfo *entries;
  /**
   * Number of entries in the array.
   * **Read-only** — do not modify.
   */
  uint32_t count;
} AetherFileList;

/**
 * Result of archive verification.
 */
typedef struct AetherVerifyResult {
  /**
   * Total number of blocks in the archive.
   */
  uint32_t total_blocks;
  /**
   * Number of blocks that verified successfully.
   */
  uint32_t verified_blocks;
  /**
   * Number of corrupted blocks detected.
   */
  uint32_t corrupted_count;
  /**
   * 1 if all blocks verified, 0 if any corruption detected.
   */
  int32_t is_ok;
} AetherVerifyResult;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Return a **caller-owned** copy of the last error message, or `NULL` if no
 * error has occurred.
 *
 * The caller must free the returned pointer with [`aether_error_free`].
 *
 * # H1 security fix
 *
 * Previous versions returned a borrowed pointer into thread-local storage,
 * which became dangling after the next FFI call. This version returns an
 * owned copy that is valid until explicitly freed.
 */
char *aether_last_error(void);

/**
 * Free an error string returned by [`aether_last_error`].
 *
 * No-op if `err` is `NULL`.
 */
void aether_error_free(char *err);

/**
 * Return the library version string (e.g. "0.2.2").
 *
 * The returned pointer is valid for the lifetime of the library and must
 * **not** be freed by the caller.
 */
const char *aether_version(void);

/**
 * Check if the library has been used. Useful for C consumers that want to
 * verify before calling `dlclose`.
 *
 * Returns 1 if any FFI function has been called, 0 otherwise.
 */
int32_t aether_is_active(void);

/**
 * Create a new compressor with the specified predictor.
 *
 * # M1 security fix
 *
 * Accepts a raw `u16` instead of the enum type to prevent undefined
 * behavior when C callers pass out-of-range values.
 *
 * Returns `NULL` on failure (check `aether_last_error()`).
 */
struct AetherCompressor *aether_compressor_new(uint16_t predictor_id);

/**
 * Set the maximum number of concurrent compression threads.
 *
 * Set to 0 for unlimited (uses all available cores).
 * Default is 4 for memory backpressure.
 *
 * # M3 security fix
 *
 * Takes `*mut` consistently with other mutating functions.
 *
 * # Fix #14
 *
 * Returns `AETHER_OK` on success, `AETHER_ERR_NULL_PTR` if compressor
 * is `NULL`. Previously returned `void`, silently ignoring null pointers.
 */
__attribute__((warn_unused_result))
int32_t aether_compressor_set_max_threads(struct AetherCompressor *compressor,
                                          uint32_t max_threads);

/**
 * Free a compressor handle and set the caller's pointer to `NULL`.
 *
 * No-op if `*compressor` is `NULL` or `compressor` is `NULL`.
 *
 * # H2 security fix
 *
 * Accepts `*mut *mut` so the caller's pointer is nulled after free,
 * preventing double-free and use-after-free bugs.
 */
void aether_compressor_free(struct AetherCompressor **compressor);

/**
 * Compress files into a `.aet` archive.
 *
 * - `base_dir`: root directory for resolving relative file paths.
 * - `file_paths`: array of C strings with file paths relative to `base_dir`.
 * - `file_count`: number of entries in `file_paths`.
 * - `output_path`: path for the output `.aet` archive.
 *
 * # M3 security fix
 *
 * Takes `*mut` for the compressor handle for consistent aliasing semantics.
 *
 * Returns `AETHER_OK` (0) on success, negative error code on failure.
 */
__attribute__((warn_unused_result))
int32_t aether_compress(struct AetherCompressor *compressor,
                        const char *base_dir,
                        const char *const *file_paths,
                        uint32_t file_count,
                        const char *output_path);

/**
 * Create a new decompressor with the specified predictor.
 *
 * # M1 security fix
 *
 * Accepts a raw `u16` instead of the enum type to prevent undefined
 * behavior when C callers pass out-of-range values.
 *
 * Returns `NULL` on failure (check `aether_last_error()`).
 */
struct AetherDecompressor *aether_decompressor_new(uint16_t predictor_id);

/**
 * Create a decompressor that auto-detects the predictor from an archive.
 *
 * Reads the archive header to determine which predictor was used during
 * compression, then creates a decompressor configured for that predictor.
 *
 * Returns `NULL` on failure (check `aether_last_error()`).
 */
struct AetherDecompressor *aether_decompressor_auto(const char *archive_path);

/**
 * Free a decompressor handle and set the caller's pointer to `NULL`.
 *
 * No-op if `*decompressor` is `NULL` or `decompressor` is `NULL`.
 *
 * # H2 security fix
 *
 * Accepts `*mut *mut` so the caller's pointer is nulled after free,
 * preventing double-free and use-after-free bugs.
 */
void aether_decompressor_free(struct AetherDecompressor **decompressor);

/**
 * Extract all files from an archive to the given output directory.
 *
 * # M4 security fix
 *
 * Validates that no extracted file path escapes the output directory
 * (zip-slip protection). If a path traversal is detected, returns
 * `AETHER_ERR_PATH_TRAVERSAL` (-7).
 *
 * # Security: output directory requirements
 *
 * The output directory (`output_dir`) **must not** be writable by untrusted
 * users. Symlink and path-traversal checks are performed before extraction
 * begins, but a local attacker with write access to the output tree can
 * race the check (TOCTOU) by replacing a directory with a symlink between
 * validation and the actual file write. For maximum safety, extract into a
 * directory owned exclusively by the calling process (e.g. a `mkdtemp`
 * result with `0700` permissions).
 *
 * Returns `AETHER_OK` (0) on success, negative error code on failure.
 */
__attribute__((warn_unused_result))
int32_t aether_extract_all(struct AetherDecompressor *decompressor,
                           const char *archive_path,
                           const char *output_dir);

/**
 * Extract a single file from an archive.
 *
 * - `file_path`: the path within the archive to extract.
 * - `output_path`: destination file path on disk.
 *
 * # M4 security fix
 *
 * Validates that the in-archive `file_path` does not contain path traversal.
 *
 * # Security: caller responsibility for `output_path`
 *
 * The `output_path` is **chosen by the caller** and is not validated against
 * a base directory. The caller is responsible for ensuring that `output_path`
 * is a safe location. The parent directory of `output_path` is checked for
 * symlinks, but the caller should still sanitize this value if it originates
 * from untrusted input.
 *
 * Returns `AETHER_OK` (0) on success, negative error code on failure.
 */
__attribute__((warn_unused_result))
int32_t aether_extract_file(struct AetherDecompressor *decompressor,
                            const char *archive_path,
                            const char *file_path,
                            const char *output_path);

/**
 * List all files in an archive.
 *
 * On success, `*list_out` is populated with a heap-allocated
 * [`AetherFileList`] containing the file entries and count.
 *
 * The caller must free the result with [`aether_file_list_free`].
 *
 * Returns `AETHER_OK` (0) on success, negative error code on failure.
 */
__attribute__((warn_unused_result))
int32_t aether_list(struct AetherDecompressor *decompressor,
                    const char *archive_path,
                    struct AetherFileList **list_out);

/**
 * Fix #12: safe accessor — return the number of entries in a file list.
 *
 * Returns 0 if `list` is `NULL`.
 */
uint32_t aether_file_list_count(const struct AetherFileList *list);

/**
 * Fix #12: safe accessor — return a pointer to the `index`-th file info entry.
 *
 * Returns `NULL` if `list` is `NULL` or `index` is out of bounds.
 * The returned pointer is valid until [`aether_file_list_free`] is called.
 */
const struct AetherFileInfo *aether_file_list_get(const struct AetherFileList *list,
                                                  uint32_t index);

/**
 * Free a file list returned by [`aether_list`] and null the caller's pointer.
 *
 * No-op if `*list` is `NULL` or `list` is `NULL`.
 *
 * # H3 security fix
 *
 * The count is now embedded in the [`AetherFileList`] struct, so the caller
 * cannot pass an incorrect count. This eliminates the heap-corruption risk
 * from the previous API where count was a separate parameter.
 *
 * # Fix #8
 *
 * Now accepts `*mut *mut` to null the caller's pointer after free,
 * consistent with the H2 pattern used by compressor/decompressor free.
 *
 * # Fix #7
 *
 * Eliminates aliasing UB: uses a single `from_raw_parts_mut` to free both
 * the path strings and the entries array without creating overlapping mutable
 * references.
 */
void aether_file_list_free(struct AetherFileList **list);

/**
 * Verify the integrity of an archive.
 *
 * On success, `*result_out` is populated with verification details.
 *
 * Returns `AETHER_OK` (0) on success (even if corruption is detected — check
 * `result_out->is_ok`). Returns a negative error code only on I/O or parsing errors.
 */
__attribute__((warn_unused_result))
int32_t aether_verify(struct AetherDecompressor *decompressor,
                      const char *archive_path,
                      struct AetherVerifyResult *result_out);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* AETHER_H */
